CREATE TABLE IF NOT EXISTS password_reset_tokens(
    ID SERIAL PRIMARY KEY,
    user_id INTEGER REFERENCES users(ID),
    token_hash text,
    EXPIRES_AT TIMESTAMPTZ DEFAULT NOW(),
    USED_AT TIMESTAMPTZ, 
    CREATED_AT TIMESTAMPTZ DEFAULT NOW()
)